name: designer_chock
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  pin_code_fields: ^7.4.0
  contained_tab_bar_view: ^0.8.0
  http: ^0.13.4
  like_button: ^2.0.4
  share_plus: ^4.0.10
  toast: ^0.3.0
  shared_preferences: ^2.0.15
  photo_view: ^0.14.0
  image_cropper: ^2.0.3
  image_picker: ^0.8.5+3







dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/designer-chowk-logo_eng.png
    - images/mask_group.png
    - images/edit.png
    - images/sign-out-alt.png
    - images/picture.png
    - images/wxr.png
    - images/Converted.png
    - images/mask.png
    - images/home.png

  fonts:
    - family: GilroyBold
      fonts:
        - asset: fonts/Gilroy-Bold.ttf
          weight: 700


    - family: GilroySemiBold
      fonts:
        - asset: fonts/Gilroy-SemiBold.ttf
          weight: 600

    - family: GilroyMedium
      fonts:
        - asset: fonts/Gilroy-Medium.ttf
          weight: 500

    - family: GilroyRegular
      fonts:
        - asset: fonts/Gilroy-Regular.ttf
          weight: 400

    - family: GilroyLight
      fonts:
        - asset: fonts/Gilroy-Light.ttf
          weight: 300









